name: CD - Deploy to AWS

on:
  workflow_run:
    workflows: ["Auto Unit Test"]  # Reference the name of your test workflow
    types:
      - completed  # This triggers when the referenced workflow finishes
  workflow_dispatch:

jobs: 
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start SSH agent and add EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY}}" > ec2-key.pem
          chmod 600 ec2-key.pem     # Set the permissions of the key file
          eval "$(ssh-agent -s)"
          ssh-add ec2-key.pem

      # build first then deploy

      - name: SSH into EC2 and clone our Phase-2 Repository
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@ec2-${{secrets.EC2_HOST}}.us-east-2.compute.amazonaws.com << 'EOF'
          cd /home/ec2-user
          git clone https://github.com/FA2024-ECE-461-Project/Phase2-Code.git


      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/Phase2-Code
            sudo cp -r src/frontend/* /var/www/html
            sudo systemctl restart nginx