- name: SSH into EC2 and git-pull our Phase-2 Repository
  run: |
     ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ secrets.EC2_HOST }} << EOF
     cd /home/ec2-user/Phase2-Code/

    # Stash local changes before git pull
     git stash --include-untracked || echo "Nothing to stash"
     git pull

    # Install backend dependencies
    rm -rf node_modules package-lock.json
    npm install

    # Install dependencies for frontend
    cd frontend/
    rm -rf node_modules package-lock.json
    npm install
    npm run build

    cd ../
    # Execute deployment script on EC2
    sudo systemctl restart myapp.service
    sudo systemctl restart caddy
    EOF
