name: CD - Deploy to AWS

on:
  workflow_run:
    workflows: ["Auto Unit Test"] # Reference the name of your test workflow
    types:
      - completed # This triggers when the referenced workflow finishes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY}}" > ec2-key.pem
          chmod 600 ec2-key.pem     # Set the permissions of the key file
          eval "$(ssh-agent -s)"
          ssh-add ec2-key.pem

      # Later goal: build first then deploy

      # we have already cloned "Phase-2 code" to AWS EC2 already
      - name: SSH into EC2 and git-pull our Phase-2 Repository
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@ec2-${{secrets.EC2_HOST}}.us-east-2.compute.amazonaws.com << 'EOF'
          cd /home/ec2-user/Phase2-Code/

          # Stash local changes before git pull
          git stash --include-untracked || echo "Nothing to stash"
          git pull

          # Install backend dependencies
          rm -rf node_modules package-lock.json
          npm install

          # Install dependencies for frontendd
          cd frontend/
          rm -rf node_modules package-lock.json
          npm install
          npm run build

          cd ../
          # Execute deployment script on EC2        
          sudo systemctl restart myapp.service
          sudo systemctl restart caddy      
