name: CD - Deploy to AWS

on:
  workflow_run:
    workflows: ["Auto Unit Test"]  # Reference the name of your test workflow
    types:
      - completed  # This triggers when the referenced workflow finishes
  workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/Phase2-Code"

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/Phase2-Code
            sudo cp -r src/frontend/* /var/www/html
            sudo systemctl restart nginx