name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    container: node:18.17.1 # specify the container to run the tests in (this may save some time)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        # only install dependencies if package.json is found
        # stops the workflow if package.json is not found
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found in branch to be merged in"
            exit 1
          fi

      # Run ESLint to check for style and linting issues:
      # run the lint script (fix all auto-fixable issues)
      # have it always exit true and compute lint score at the end
      - name: Run ESLint
        run: |
          npm run lint
          echo "ESLint completed successfully"