name: Move issue to 'In Progress' on pull request

on:
  pull_request:
    branches: [main]
    types: [opened]
  # create a workflow_dispatch event to manually trigger the workflow: better for future debugging
  workflow_dispatch:

jobs:
  move_issue_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # dynamically set ISSUE_NUMBER env variable with echo
      - name: Get linked issue number
        id: get_issue_number
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | head -1 | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER"
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
      
      - name: Move issue to 'In Progress'
        if: github.env.ISSUE_NUMBER != '' 
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: '461 Phase2'  
          column: 'In Progress'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
